server:
  port: 8093
  
spring:
  data:
    mongodb:
      host: 192.168.1.100
      port: 27017
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.100:8082/eureka/
      
microservice:
  web:
    association: http://association-service/association
    account: http://account-service/account
    movement: http://movement-service/movement