server:
  port: 8085
  
spring:
  data:
    mongodb:
      host: 192.168.1.100
      port: 27017
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.100:8082/eureka/
      
microservice:
  web:
    customer: http://customer-service/customer