server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
        - id: product-service
          uri: http://localhost:8085/
          predicates:
            - Path=/product/**
        - id: acquisition-service
          uri: lb://acquisition-service
          predicates:
            - Path=/acquisition/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
