server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.100:8082/eureka/
      
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 8
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 3s
    instances:
      customer:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      customer:
        base-config: default
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://192.168.1.100:8084
          predicates:
            - Path=/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: customer
                statusCodes: 500
        - id: creditcard-service
          uri: http://192.168.1.100:8085
          predicates:
            - Path=/creditcard/**
        - id: acquisition-service
          uri: http://192.168.1.100:8086
          predicates:
            - Path=/acquisition/**
        - id: account-service
          uri: http://192.168.1.100:8087
          predicates:
            - Path=/account/**
        - id: credit-service
          uri: http://192.168.1.100:8088
          predicates:
            - Path=/credit/**
        - id: deposit-service
          uri: http://192.168.1.100:8089
          predicates:
            - Path=/deposit/**
        - id: movement-service
          uri: http://192.168.1.100:8090
          predicates:
            - Path=/movement/**
        - id: association-service
          uri: http://192.168.1.100:8091
          predicates:
            - Path=/association/**
        - id: transfer-service
          uri: http://192.168.1.100:8092
          predicates:
            - Path=/transfer/**
        - id: consumption-service
          uri: http://192.168.1.100:8093
          predicates:
            - Path=/consumption/**
        - id: retire-service
          uri: http://192.168.1.100:8094
          predicates:
            - Path=/retire/**
