server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.100:8082/eureka/
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://192.168.1.100:8084
          predicates:
            - Path=/customer/**
        - id: creditcard-service
          uri: http://192.168.1.100:8085
          predicates:
            - Path=/creditcard/**
        - id: acquisition-service
          uri: http://192.168.1.100:8086
          predicates:
            - Path=/acquisition/**
        - id: account-service
          uri: http://192.168.1.100:8087
          predicates:
            - Path=/account/**
        - id: credit-service
          uri: http://192.168.1.100:8088
          predicates:
            - Path=/credit/**
        - id: deposit-service
          uri: http://192.168.1.100:8089
          predicates:
            - Path=/deposit/**
        - id: movement-service
          uri: http://192.168.1.100:8090
          predicates:
            - Path=/movement/**
